(exo
	(:import :extern #:trivial-gray-streams)
	(:export :extern
		#:*default-eol-style*
		#:*default-little-endian*
		#:*substitution-char*
		#:accept-overlong-sequence
		#:char-length
		#:external-format-condition
		#:external-format-condition-external-format
		#:external-format-eol-style
		#:external-format-error
		#:external-format-encoding-error
		#:external-format-equal
		#:external-format-id
		#:external-format-little-endian
		#:external-format-name
		#:flexi-input-stream
		#:flexi-output-stream
		#:flexi-io-stream
		#:flexi-stream-bound
		#:flexi-stream-column
		#:flexi-stream-external-format
		#:flexi-stream-element-type
		#:flexi-stream-element-type-error
		#:flexi-stream-element-type-error-element-type
		#:flexi-stream-error
		#:flexi-stream-out-of-sync-error
		#:flexi-stream-position
		#:flexi-stream-stream
		#:get-output-stream-sequence
		#:in-memory-stream
		#:in-memory-stream-closed-error
		#:in-memory-stream-error
		#:in-memory-stream-position-spec-error
		#:in-memory-stream-position-spec-error-position-spec
		#:in-memory-input-stream
		#:in-memory-output-stream
		#:make-flexi-stream
		#:make-external-format
		#:make-in-memory-input-stream
		#:make-in-memory-output-stream
		#:octet
		#:octet-length
		#:octets-to-string
		#:output-stream-sequence-length
		#:peek-byte
		#:string-to-octets
		#:unread-byte
		#:vector-stream
		#:vector-stream-vector
		#:with-input-from-sequence
		#:with-output-to-sequence
		#:stream-read-char
		;; for test
		#:with-unique-names
		#:with-rebinding
		#:char*
		#:normalize-external-format
		#:+name-map+
		#:+shortcut-map+
		#:+buffer-size+
		#:defconstant
		#:*substitution-char*)
	(:bundle
		#:mapping
		#:ascii
		#:koi8-r
		#:mac
		#:iso-8859
		#:enc-cn-tbl
		#:code-pages
		#:specials
		#:util
		#:conditions
		#:external-format
		#:length
		#:encode
		#:decode
		#:in-memory
		#:stream
		#+:lispworks #:lw-char-stream
		#:output
		#:input
		#:io
		#:strings))